# Generated by Django 4.2.11 on 2024-08-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='slug',
            new_name='title_slug',
        ),
    ]
