# Generated by Django 4.2.11 on 2024-08-30 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_slug_listing_title_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
