# Generated by Django 4.2.11 on 2024-09-01 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_current_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='soldto',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
